import { Destination, Interest } from './type';

export const mockInterests: Interest[] = [
    { id: '8e110925-89cc-4a26-bde6-f36363fd6e01', name: 'Adventure', icon: '🏞️' },
    { id: '8e110925-89cc-4a26-bde6-f36363fd6e02', name: 'Culture', icon: '🏛️' },
    { id: '8e110925-89cc-4a26-bde6-f36363fd6e03', name: 'Relaxation', icon: '🏖️' },
    { id: '8e110925-89cc-4a26-bde6-f36363fd6e04', name: 'Nature', icon: '🌲' },
    { id: '8e110925-89cc-4a26-bde6-f36363fd6e05', name: 'Food & Drink', icon: '🍽️' },
    { id: '8e110925-89cc-4a26-bde6-f36363fd6e06', name: 'History', icon: '🏺' },
    { id: '8e110925-89cc-4a26-bde6-f36363fd6e07', name: 'Wildlife', icon: '🦁' },
    { id: '8e110925-89cc-4a26-bde6-f36363fd6e08', name: 'Shopping', icon: '🛍️' },
];

export const mockDestinations: Destination[] = [
    {
        id: '1',
        country: 'France',
        city: 'Paris',
        description: 'The city of lights and love, known for its iconic landmarks such as the Eiffel Tower, Louvre Museum, and Notre-Dame Cathedral.',
        latitude: 48.8566,
        longitude: 2.3522,
        activities: [
            {
                id: 'a1',
                name: 'Eiffel Tower Visit',
                description: 'Climb to the top of the Eiffel Tower for a breathtaking view of Paris.',
                date: '2023-10-01',
                time: '10:00 AM',
                location: 'Eiffel Tower, Paris',
                budget: 25,
            },
            {
                id: 'a2',
                name: 'Louvre Museum Tour',
                description: 'Explore the world-famous art collections at the Louvre Museum.',
                date: '2023-10-02',
                time: '2:00 PM',
                location: 'Louvre Museum, Paris',
                budget: 15,
            },
        ],
        budget: 2000,

    },
    {
        id: '2',
        country: 'Japan',
        city: 'Tokyo',
        description: 'A bustling metropolis that seamlessly blends tradition and modernity, with attractions like the historic Senso-ji Temple and the vibrant Shibuya Crossing.',
        latitude: 35.6895,
        longitude: 139.6917,
        activities: [
            {
                id: 'a3',
                name: 'Senso-ji Temple Visit',
                description: "Visit Tokyo's oldest temple and explore the surrounding Nakamise shopping street.",
                date: '2023-11-05',
                time: '11:00 AM',
                location: 'Senso-ji Temple, Tokyo',
                budget: 0,
            },
            {
                id: 'a4',
                name: 'Shibuya Crossing Experience',
                description: "Experience the world's busiest pedestrian crossing and enjoy shopping in the area.",
                date: '2023-11-06',
                time: '6:00 PM',
                location: 'Shibuya Crossing, Tokyo',
                budget: 50,
            },
        ],
        budget: 2500,
    },
    {
        id: '3',
        country: 'Spain',
        city: 'Barcelona',
        description: 'A vibrant city famed for its art, architecture, and lively beaches, with highlights like the Sagrada Familia and Park Güell.',
        latitude: 41.3851,
        longitude: 2.1734,
        activities: [],
        budget: 1800,
    },
    {
        id: '4',
        country: 'USA',
        city: 'New York City',
        description: 'The city that never sleeps, packed with iconic sights such as Times Square, Central Park, and the Statue of Liberty.',
        latitude: 40.7128,
        longitude: -74.0060,
        activities: [],
        budget: 3000,
    },
    {
        id: '5',
        country: 'Egypt',
        city: 'Cairo',
        description: 'A historical treasure trove by the Nile, home to ancient pyramids, bustling bazaars, and the unforgettable Egyptian Museum.',
        latitude: 30.0444,
        longitude: 31.2357,
        activities: [],
        budget: 1600,
    },
    {
        id: '6',
        country: 'Australia',
        city: 'Sydney',
        description: 'A harbor city recognized for the Sydney Opera House, beautiful Bondi Beach, and a lively multicultural scene.',
        latitude: -33.8688,
        longitude: 151.2093,
        activities: [],
        budget: 2800,
    },
]
